name: cache

on:
  push:
    branches: ["main"]

jobs:
  cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Python setuptools using Homebrew
        if: ${{ matrix.os == 'ubuntu-latest' && github.event_name != 'pull_request' }}
        run: brew install python-setuptools

      - name: Install deps
        run: pnpm install
