name: CD

on:
  schedule:
  - cron: "0 */2 * * *"

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}
  DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get new commits
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '2 hours ago' | wc -l)" >> $GITHUB_ENV

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps (with cache)
        run: pnpm install

      - name: Apply database migrations
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        run: pnpm db:migrate:prod

      - name: Render deploy
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        run: |
          curl "$DEPLOY_URL"
