name: CI

on:
  pull_request:
  merge_group:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  EXPO_OWNER: ${{ secrets.EXPO_OWNER }}
  EXPO_PROJECT_ID: ${{ secrets.EXPO_PROJECT_ID }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm turbo lint

      - name: Check workspaces
        run: pnpm manypkg check

      # - name: Check Expo dependencies
      #   run: (cd apps/expo && pnpm lint:expo)
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install deps
        run: pnpm install

      - name: Check formatting
        run: pnpm turbo format
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm turbo typecheck build

  android:
    runs-on: ubuntu-latest

    steps:
    - name: Setup repo
      # if: github.event_name != 'pull_request'
      uses: actions/checkout@v4

    - name: Setup pnpm
      # if: github.event_name != 'pull_request'
      uses: pnpm/action-setup@v3.0.0

    - name: Setup Node
      # if: github.event_name != 'pull_request'
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Setup Expo and EAS
      # if: github.event_name != 'pull_request'
      uses: expo/expo-github-action@v8
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest
        packager: pnpm

    - name: Setup Java 17
      # if: github.event_name != 'pull_request'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install deps
      # if: github.event_name != 'pull_request'
      run: pnpm i

    - name: Build app
      # if: github.event_name != 'pull_request'
      run: |
        cd apps/expo && eas build --local \
          --non-interactive \
          --output=./app-build \
          --platform=android \
          --profile=development

  ios:
    runs-on: macos-latest
    steps:
      - name: Setup repo
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4

      - name: Setup pnpm
        if: github.event_name != 'pull_request'
        uses: pnpm/action-setup@v3.0.0
      
      - name: Setup Node
        if: github.event_name != 'pull_request'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Setup Expo
        if: github.event_name != 'pull_request'
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: pnpm

      - name: Install Python setuptools using Homebrew
        if: github.event_name != 'pull_request'
        run: brew install python-setuptools

      - name: Setup Cocoapods
        if: github.event_name != 'pull_request'
        uses: maxim-lobanov/setup-cocoapods@v1 
        with:
          version: latest

      - name: Install deps
        if: github.event_name != 'pull_request'
        run: pnpm i

      - name: Build iOS app
        if: github.event_name != 'pull_request'
        run: |
          cd apps/expo && eas build --local \
            --non-interactive \
            --output=./app-build \
            --platform=ios \
            --profile=preview
