name: Expo

on:
  pull_request:
  merge_group:

env:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  EXPO_OWNER: ${{ secrets.EXPO_OWNER }}
  EXPO_PROJECT_ID: ${{ secrets.EXPO_PROJECT_ID }}

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    - name: Setup repo
      if: github.event_name != 'pull_request'
      uses: actions/checkout@v4

    - name: Setup pnpm
      if: github.event_name != 'pull_request'
      uses: pnpm/action-setup@v2.4.0

    - name: Setup Node
      uses: actions/setup-node@v4
      if: github.event_name != 'pull_request'
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Setup Expo and EAS
      uses: expo/expo-github-action@v8
      if: github.event_name != 'pull_request'
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest
        packager: pnpm

    - name: Install deps
      if: github.event_name != 'pull_request'
      run: pnpm i

    - name: Build app
      if: github.event_name != 'pull_request'
      run: |
        cd apps/expo && eas build --local \
          --non-interactive \
          --output=./app-build \
          --platform=android \
          --profile=development

  ios:
    runs-on: macos-latest

    steps:
    - name: Setup repo
      if: github.event_name != 'pull_request'
      uses: actions/checkout@v4

    - name: Setup pnpm
      if: github.event_name != 'pull_request'
      uses: pnpm/action-setup@v2.4.0

    - name: Setup Node
      if: github.event_name != 'pull_request'
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Setup Expo and EAS
      if: github.event_name != 'pull_request'
      uses: expo/expo-github-action@v8
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest
        packager: pnpm

    - name: Install deps
      if: github.event_name != 'pull_request'
      run: pnpm i

    - name: Build app
      if: github.event_name != 'pull_request'
      run: |
        cd apps/expo && eas build --local \
          --non-interactive \
          --output=./app-build \
          --platform=ios \
          --profile=preview
